services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: |
      poetry install
      ./install_problematic_lib.sh
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:main_app
    envVars:
      - key: UPSTASH_REDIS_URL
        value: "redis://:AcHYAAIjcDFmZjIxOTE3YmVhMmI0NDlkYTg3YjJjNGUyMTEyMzNmMnAxMA@deciding-scorpion-49624.upstash.io:6379/0"

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: |
      poetry install
      ./install_problematic_lib.sh
    startCommand: celery -A celery_app worker --loglevel=info
    envVars:
      - key: UPSTASH_REDIS_URL
        value: "redis://:AcHYAAIjcDFmZjIxOTE3YmVhMmI0NDlkYTg3YjJjNGUyMTEyMzNmMnAxMA@deciding-scorpion-49624.upstash.io:6379/0"

